version: "3.7"

services:
  webserver:
    build: 
      context: ./bin/webserver
    container_name: '${PROJECT_NAME:?nom de porjet manquant}-webserver'
    restart: unless-stopped
    labels:
      traefik.frontend.rule: "Host:${APP_HOSTS}"
      traefik.backend: "Drupal-${APP_HOST}"
      traefik.docker.network: "traefik_default"
      traefik.port: 80
    depends_on:
      - mysql
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
    networks:
      - default_net
      - traefik_default

  mysql:
    image: mysql:5.6
    container_name: '${PROJECT_NAME:?nom de porjet manquant}-mysql'
    restart: unless-stopped
    labels:
      traefik.enable: "false"
    volumes: 
      - dbdata:/var/lib/mysql
      - ./data/mysql/db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - default_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: '${PROJECT_NAME:?nom de porjet manquant}-phpmyadmin'
    environment:
      PMA_HOST: mysql
    labels:
      traefik.frontend.rule: "Host:phpmyadmin.dev.${APP_HOST}.${END_HOST:-fr}"
      traefik.docker.network: "traefik_default"
      traefik.port: 80
    restart: unless-stopped
    networks:
      - default_net
      - traefik_default

networks:
  default_net:
  traefik_default:
    external: true

volumes:
  dbdata: